version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${JOBTRACKER_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${JOBTRACKER_DB_PWD}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
